config/routes.rb
Rails.application.routes.draw do
  devise_for :writers

  resources :posts
  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/categoly.rb
class Categoly < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_writer!, only: [:new, :create, :edit, :update, :destroy]
  def new
    @post = Post.new
  end
  def show
    #@post = Post.find(params[:id])
  end
  def index
    #@posts = Post.page(params[:page]).per(2)
    #@posts = Post.all
    @q = Post.search(params[:q])
    @posts = @q.result.page(params[:page])
  end
  def create
    #フォームからデータを受け取る
    @post = Post.new(post_params)
    @post.save
    #show.html.erbに飛ばす
    redirect_to "/posts/#{@post.id}"
  end
  def edit
    #@post = Post.find(params[:id])
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end



  def update
    @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  private
  def set_post
   @post = Post.find(params[:id])
 end
  def post_params
    # params.require(:key).permit(:filter)
    params.require(:post).permit(
      :title,
      :body,
      :category_id
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def find_category_title(category_id)
    category = Category.find(category_id)
    category.title
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

 <!-- Optional theme -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

 <!-- Latest compiled and minified JavaScript -->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">My Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">

    </div><!-- /.navbar-collapse -->
      <ul class="nav navbar-nav navbar-right">
      <% if writer_signed_in? %>
        <p class="navbar-text">
          <%#= current_writer.family_name %>
          <%#= current_writer.given_name %>さんようこそ！
        </p>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "設定変更", edit_writer_registration_path %></li>
          <li><%= link_to "ログアウト" ,destroy_writer_session_path, method: :delete %></li>
          <li><a href="/posts/new">投稿する</a></li>
        </ul>
      <% else %>
        <li><%= link_to "新規登録", new_writer_registration_path %></li>
        <li><%= link_to "ログイン", new_writer_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <div class="row">

  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>投稿記事編集フォーム</h1>
  <%= form_for @post, url: { action: :update } do |f| %>
  <p>タイトル：<br>
    <%= f.text_field :title %>
  </p>
  <div class="form-group">
     <%= f.label "カテゴリ" %>
     <%= f.collection_select(:category_id, Category.all, :id, :title, class: "form-control") %>
   </div>
   <div class="form-group">
     <%= f.label "本文" %>
     <%= f.text_area :body, class: "form-control" %>
   </div>
  <%= f.submit "編集する" %>
  <%= link_to '戻る', posts_path %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>ひとり交換日記</h1>

<%= search_form_for @q do |f| %>
<div class="row">
    <div class="col-sm-3 col-xs-12">
      <div class="form-group">
        <%= f.search_field :title_or_body_cont, class: "form-control input-sm" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 text-center">
      <%= f.submit "検索", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

<div class="col-md-8">
<% @posts.each do |post| %>
    <div class="article">
      <h2><%= post.title %></h2>
      <p><%= post.category %> <%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
      <p><%= truncate(post.body, length: 50) %></p>
      <p>
        <%= link_to "続きを読む", post_path(post.id), class: 'btn btn-default' %>
        <%= link_to '編集', edit_post_path(post) ,class:"btn btn-info btn-xs"%>
        <%= link_to '削除', post_path(post),
                  method: :delete, data: { confirm: '削除しますか？' },class:"btn btn-danger btn-xs" %>
      </p>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>


<div class="col-md-4">
  <div class="thumbnail">
    <% author = Author.first %>
    <img src="<%= author.image_url %>" alt="著者イメージ" >
    <div class="caption">
      <h3><%= author.name %></h3>
      <p><%= author.description %></p>
    </div>
  </div>
  <div class="list-group">
  <% @posts.each_with_index do |post, index| %>
      <%# ６個目以上の記事の場合はBreak（each文をその場で終わらせる） %>
      <% if index >= 5
           break
         end
      %>
      <%# link_to post.title, post_path(post.id), class: "list-group-item" %>
      <a href="/posts/<%= post.id %>" class="list-group-item"><%= post.title %></a>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-12">
<h1>新規投稿フォーム</h1>
<%= form_for @post, url: { action: :create } do |f| %>
<div class="form-group">
<p>タイトル：<br>
  <%= f.text_field :title %>
</p>
</div>
<div class="form-group">
<p>カテゴリー：<br>
  <%= f.text_field :category %>
</p>
</div>
<div class="form-group">
<p>本文：<br>
  <%= f.text_area :body ,class:"form-control"%>
</p>
<%= f.submit "登録する",class:"btn btn-primary" %>
<%= link_to '戻る', posts_path,class:"btn btn-info" %>

<% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <p>
    <b>タイトル：<%= @post.title %></b>
  </p>

  <p>
    <b>カテゴリー：<%= find_category_title(@post.category_id) %></b>
  </p>
  <p>
    <b>投稿日：<%= @post.created_at %></b>
  </p>
  <hr>
  <p>
    <b>本文：<%= simple_format(@post.body) %></b>
  </p>

  <hr>
  <%= link_to '編集する',edit_post_path %>
  <%= link_to '削除する',post_path,method: :delete , data: { confirm: '削除しますか？' } %>
  <%= link_to '戻る', posts_path %>
</div>